/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Expose Prometheus metrics
         * @description Returns application performance and system metrics in Prometheus text format.         This endpoint is intended for scraping by Prometheus or compatible monitoring tools.         The response contains metrics about Fastify routes, event loop lag, memory usage,         and any custom counters registered via the Prometheus client.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable 2FA (init setup)
         * @description Generates a TOTP secret + QR code for the user to scan with Google Authenticator.
         */
        post: operations["enable2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify TOTP code
         * @description Verify a 6-digit time-based code from the user’s authenticator app.
         */
        post: operations["verifyTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login-totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with TOTP code
         * @description Login with a 6-digit time-based code from the user’s authenticator app and issue a session.
         */
        post: operations["loginTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify backup code
         * @description Verify a one-time backup code (issued when enabling 2FA). Each code can only be used once.
         */
        post: operations["verifyBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable 2FA
         * @description Clears the stored secret and disables 2FA for the user.
         */
        post: operations["disable2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate backup codes for 2FA
         * @description Generates 10 single-use backup codes, stores them hashed, and returns plaintext codes once.
         */
        post: operations["backup2FA"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/check-2fa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check if 2FA is enabled for a user
         * @description This endpoint verifies whether a given username or email has two-factor authentication (2FA) enabled.         It is typically used before login to determine if a second verification step is required.
         */
        post: operations["isF2aEnabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login (issue access & refresh, or request 2FA)
         * @description Authenticate with username/email + password. If 2FA is enabled,         the server responds with `f2a_required` instead of issuing tokens.         If the account has not been activated, the server responds with         'activation_required' instead of issuing tokens.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register new account
         * @description Create a new user account with username, email, and password.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token (rotate refresh)
         * @description Uses the HttpOnly refresh cookie to validate and rotate the refresh token, then returns a new access token.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout (revoke refresh)
         * @description Deletes the stored refresh token tied to the cookie and clears the cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-pwd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset email
         * @description Initiates the password reset process for an account associated with the given email.         This endpoint verifies the provided reCAPTCHA token, creates a reset token,         stores it in the database, and sends a password reset email to the user.         The email will contain a reset link valid for 1 hour.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-pwd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a user's password using a reset token
         * @description Completes the password reset process. The client must provide the reset token         received by email and the new password. The token is verified for validity, usage,         and expiration before the password is updated. The token is marked as used after success.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the activation link to the user email adresse.
         * @description Emit a new token if no token has beed found of if the old one has expired.
         */
        post: operations["activateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/activate/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activate a user account using an activation token
         * @description Activates a newly registered user account using the activation link         sent by email. The endpoint verifies the activation token for validity,         ensures it has not been used, and marks both the token and user as activated.         Expired or invalid tokens will result in appropriate error responses.
         */
        get: operations["activateUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start OAuth flow
         * @description Redirects to the OAuth provider’s authorization URL with proper state and next cookie set.
         */
        get: operations["oauthStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback
         * @description Handles the OAuth2 provider redirect, exchanges code for profile, and issues tokens.
         */
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user sessions
         * @description Returns all active and historical refresh token sessions for the authenticated user, including device info, IP address, timestamps, and current session indicator.
         */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke user session
         * @description Revokes a specific user refresh token session, effectively logging out that session. If the current session is revoked, related authentication cookies are cleared.
         */
        post: operations["revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the current health status of the API and database.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all users (admin only)
         * @description Retrieves the full list of registered users. Access restricted to `admin` role.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authenticated user
         * @description Returns the authenticated user’s profile. Requires a valid Bearer access token.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/modify-pwd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Modify the password of the currently authenticated user
         * @description Allows an authenticated user to change their password.         For local accounts, the user must provide their current password.         For OAuth-linked accounts, the `oauth` flag can be used to skip verification.
         */
        post: operations["modifyPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics successfully retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Failed to collect or render metrics */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    enable2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verifyTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example false */
                        enabled: boolean;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid 2FA code */
                        error: string;
                        /** @example INVALID_2FA_CODE */
                        code: string;
                    };
                };
            };
        };
    };
    loginTotp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 123456 */
                    code: string;
                    userId: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example alice */
                        user: string;
                        /** @example user */
                        role: string;
                        /** @description JWT access token */
                        token: string;
                        /** @example 3600 */
                        exp: number;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid 2FA code */
                        error: string;
                        /** @example INVALID_2FA_CODE */
                        code: string;
                    };
                };
            };
        };
    };
    verifyBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 12ab-34cd */
                    code: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example alice */
                        user: string;
                        /** @example user */
                        role: string;
                        /** @description JWT access token */
                        token: string;
                        /** @example 3600 */
                        exp: number;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example This backup code was already used */
                        error: string;
                        /** @example BACKUP_EXHAUSTED */
                        code: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Something went wrong */
                        error: string;
                        /** @example INTERNAL_ERROR */
                        code: string;
                    };
                };
            };
        };
    };
    disable2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid credentials */
                        error: string;
                        /** @example USER_NOT_FOUND */
                        code: string;
                    };
                };
            };
        };
    };
    backup2FA: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @description List of plaintext backup codes (only shown once) */
                        codes: string[];
                    };
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Failed to generate backup codes */
                        error: string;
                        /** @example BACKUP_GENERATE_FAILED */
                        code: string;
                    };
                };
            };
        };
    };
    isF2aEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Username or email to check for 2FA status
                     * @example jeportie
                     */
                    user: string;
                };
            };
        };
        responses: {
            /** @description Successfully checked 2FA status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * @description Whether 2FA is enabled for the given account
                         * @example true
                         */
                        f2a_enabled: boolean;
                    };
                };
            };
            /** @description Missing or invalid user field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description User not found or unauthorized request */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid credentials */
                        error: string;
                        /** @example USER_NOT_FOUND */
                        code: string;
                    };
                };
            };
            /** @description Unexpected internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Unexpected server error */
                        error: string;
                        /** @example INTERNAL_SERVER_ERROR */
                        code: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Username or email of the account
                     * @example jeportie
                     */
                    user: string;
                    /**
                     * @description Password (3–128 characters)
                     * @example secret123
                     */
                    pwd: string;
                };
            };
        };
        responses: {
            /** @description Either a valid session OR a 2FA challenge OR unactive session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example jeportie */
                        user: string;
                        /** @example player */
                        role: string;
                        /** @description JWT access token */
                        token: string;
                        /** @example 15m */
                        exp: string;
                    } | {
                        /** @example false */
                        success: boolean;
                        /** @example true */
                        f2a_required: boolean;
                        /** @example 42 */
                        user_id: number;
                        /** @example jeportie */
                        username: string;
                    } | {
                        /** @example false */
                        success: boolean;
                        /** @example true */
                        activation_required: boolean;
                        /** @example 42 */
                        user_id: number;
                        /** @example jeportie */
                        username: string;
                    };
                };
            };
            /** @description Validation or missing fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing credentials */
                        error: string;
                        /** @example MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description Invalid credentials or unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid credentials */
                        error: string;
                        /** @example INVALID_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description Unexpected internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Unexpected server error */
                        error: string;
                        /** @example INTERNAL_SERVER_ERROR */
                        code: string;
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Username must be 6–32 chars, alphanumeric/underscore only
                     * @example jeportie_42
                     */
                    username: string;
                    /**
                     * Format: email
                     * @description Valid email address
                     * @example jeportie@42.fr
                     */
                    email: string;
                    /**
                     * @description Password (8–128 characters)
                     * @example S3curePassw0rd!
                     */
                    pwd: string;
                };
            };
        };
        responses: {
            /** @description User successfully registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example true */
                        activation_required: boolean;
                        /** @example 2 */
                        user_id: number;
                        /** @example jeportie */
                        username: string;
                    };
                };
            };
            /** @description Validation or user creation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example User already exists */
                        error: string;
                        /** @example USER_ALREADY_EXISTS */
                        code: string;
                    };
                };
            };
            /** @description Unexpected internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Unexpected server error */
                        error: string;
                        /** @example INTERNAL_SERVER_ERROR */
                        code: string;
                    };
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @description New JWT access token */
                        token: string;
                        /** @example 15m */
                        exp: string;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Session expired */
                        error: string;
                        /** @example REFRESH_EXPIRED */
                        code: string;
                    };
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example No active session */
                        error: string;
                        /** @example NO_REFRESH_COOKIE */
                        code: string;
                    };
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description The email address associated with the user account.
                     * @example jeportie@example.com
                     */
                    email: string;
                    /**
                     * @description Google reCAPTCHA verification token to prevent automated abuse.
                     * @example 03AF6jDqXyZ...
                     */
                    captcha: string;
                };
            };
        };
        responses: {
            /** @description Password reset request processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example If the email exists, we will send a link. Please check your emails. */
                        message: string;
                    };
                };
            };
            /** @description Missing or invalid fields or captcha token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing required fields */
                        error: string;
                        /** @example MISSING_FIELDS */
                        code: string;
                    };
                };
            };
            /** @description Invalid reCAPTCHA verification */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid reCAPTCHA verification */
                        error: string;
                        /** @example INVALID_reCAPTCHA */
                        code: string;
                    };
                };
            };
            /** @description No account found for the given email (silent fail for privacy) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example If the email exists, we will send a link. Please check your emails. */
                        message: string;
                    };
                };
            };
            /** @description Database or internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example The database failed */
                        error: string;
                        /** @example DB_FAIL */
                        code: string;
                    };
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Password reset token received via email (hex-encoded string).
                     * @example 5f2b9d4e6c8f4a3b9e1f2c7a6d9e0b4c3a2d1e0f9b8c7d6a5e4f3b2c1d0e9f8
                     */
                    token: string;
                    /**
                     * @description New password to set. Must meet the platform’s password policy.
                     * @example MyNewStrongP@ssw0rd
                     */
                    pwd: string;
                };
            };
        };
        responses: {
            /** @description Password successfully reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example Password has been changed. */
                        message: string;
                    };
                };
            };
            /** @description Missing required fields or token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing required fields */
                        error: string;
                        /** @example MISSING_FIELDS */
                        code: string;
                    };
                };
            };
            /** @description Invalid or expired reset token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid or expired reset token */
                        error: string;
                        /** @example INVALID_RESET_TOKEN */
                        code: string;
                    } | {
                        /** @example false */
                        success: boolean;
                        /** @example This reset token was already used */
                        error: string;
                        /** @example USED_RESET_PWD_TOKEN */
                        code: string;
                    } | {
                        /** @example false */
                        success: boolean;
                        /** @example Reset link expired */
                        error: string;
                        /** @example LINK_EXPIRED */
                        code: string;
                    };
                };
            };
            /** @description Database or internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example The database failed */
                        error: string;
                        /** @example DB_FAIL */
                        code: string;
                    };
                };
            };
        };
    };
    activateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The user_id returned after connection. */
                    user_id: number;
                };
            };
        };
        responses: {
            /** @description Link successfully send. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example Link has been successfully resent. */
                        message: string;
                    };
                };
            };
            /** @description Invalid credentials or unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid credentials */
                        error: string;
                        /** @example INVALID_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description Database or internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example The database failed */
                        error: string;
                        /** @example DB_FAIL */
                        code: string;
                    };
                };
            };
        };
    };
    activateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique activation token sent to the user's email. */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account successfully activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example Account activated successfully. */
                        message: string;
                    };
                };
            };
            /** @description Missing or invalid activation token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing activation token */
                        error: string;
                        /** @example MISSING_ACTIVATION_TOKEN */
                        code: string;
                    } | {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid or expired token */
                        error: string;
                        /** @example INVALID_OR_EXPIRED_TOKEN */
                        code: string;
                    };
                };
            };
            /** @description Activation link has expired or token already used */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Activation Token already used */
                        error: string;
                        /** @example USED_ACTIVATION_TOKEN */
                        code: string;
                    } | {
                        /** @example false */
                        success: boolean;
                        /** @example Activation link expired */
                        error: string;
                        /** @example LINK_EXPIRED */
                        code: string;
                    };
                };
            };
            /** @description Database or internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example The database failed */
                        error: string;
                        /** @example DB_FAIL */
                        code: string;
                    };
                };
            };
        };
    };
    oauthStart: {
        parameters: {
            query?: {
                /** @description Optional path to redirect after login */
                next?: string;
            };
            header?: never;
            path: {
                /** @description The OAuth provider to use */
                provider: "google" | "github" | "42";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Default Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Redirects the client to the provider’s OAuth page */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Unknown provider */
                        error: string;
                        /** @example OAUTH_PROVIDER_UNKNOWN */
                        code: string;
                    };
                };
            };
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML redirect page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid OAuth state */
                        error: string;
                        /** @example OAUTH_STATE_INVALID */
                        code: string;
                    };
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of user sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: {
                            /** @example 13c15c8d-3df2-45cb-930f-b79b5d5b29f0 */
                            id: string;
                            /** @example Mac */
                            device: string;
                            /** @example Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5_0) */
                            agent: string;
                            /** @example 192.168.1.15 */
                            ip: string;
                            /**
                             * Format: date-time
                             * @example 2025-10-29T10:32:10.000Z
                             */
                            createdAt: string;
                            /**
                             * Format: date-time
                             * @example 2025-10-31T08:22:43.000Z
                             */
                            lastActiveAt: string;
                            /**
                             * Format: date-time
                             * @example 2025-11-29T10:32:10.000Z
                             */
                            expiresAt: string;
                            /**
                             * Format: date-time
                             * @example null
                             */
                            revokedAt: string | null;
                            /** @example true */
                            current: boolean;
                        }[];
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing or invalid token */
                        error: string;
                        /** @example AUTH_MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Internal Server Error */
                        error: string;
                        /** @example INTERNAL_ERROR */
                        code: string;
                    };
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session ID (alternative to body parameter) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description ID of the session (refresh token) to revoke
                     * @example c1b2b345-6a78-4d90-81e2-1f9f9cd9b6d7
                     */
                    sessionId: string;
                };
            };
        };
        responses: {
            /** @description Session successfully revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /**
                         * @description ID of the revoked session
                         * @example c1b2b345-6a78-4d90-81e2-1f9f9cd9b6d7
                         */
                        revokedId: string;
                        /**
                         * @description True if the revoked session was the user's current active session
                         * @example false
                         */
                        currentRevoked: boolean;
                    };
                };
            };
            /** @description Session not found or already revoked */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Session not found or already revoked. */
                        message: string;
                        /** @example c1b2b345-6a78-4d90-81e2-1f9f9cd9b6d7 */
                        revokedId: string;
                    };
                };
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing or invalid token */
                        error: string;
                        /** @example AUTH_MISSING_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Internal Server Error */
                        error: string;
                        /** @example INTERNAL_ERROR */
                        code: string;
                    };
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                        /**
                         * Format: date-time
                         * @example 2025-09-05T14:30:00.000Z
                         */
                        updated_at: string | null;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Health check not found */
                        error: string;
                        /** @example HEALTH_NOT_FOUND */
                        code: string;
                    };
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        users: {
                            /** @example 1 */
                            id: number;
                            /** @example jeportie */
                            username: string;
                            /** @example jerome@example.com */
                            email: string;
                            /** @example admin */
                            role: string;
                            /**
                             * Format: date-time
                             * @example 2025-09-05T14:00:00.000Z
                             */
                            created_at: string;
                        }[];
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Unauthorized */
                        error: string;
                        /** @example UNAUTHORIZED */
                        code: string;
                        /** @example 401 */
                        status: number;
                        /** @example [User] */
                        context: string;
                    };
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Forbidden */
                        error: string;
                        /** @example FORBIDDEN */
                        code: string;
                        /** @example 403 */
                        status: number;
                        /** @example [Admin] */
                        context: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example No users found */
                        error: string;
                        /** @example NO_USERS */
                        code: string;
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        me: {
                            /** @example 1 */
                            id: number;
                            /** @example jeportie */
                            username: string;
                            /** @example jerome@example.com */
                            email: string;
                            /** @example player */
                            role: string;
                            /**
                             * Format: date-time
                             * @example 2025-09-05T14:00:00.000Z
                             */
                            created_at: string;
                            f2a_enabled?: boolean;
                            oauth?: boolean;
                        };
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Unauthorized */
                        error: string;
                        /** @example UNAUTHORIZED */
                        code: string;
                        /** @example 401 */
                        status: number;
                        /** @example [User] */
                        context: string;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example User not found */
                        error: string;
                        /** @example USER_NOT_FOUND */
                        code: string;
                    };
                };
            };
        };
    };
    modifyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The current password of the user (required for local accounts).
                     * @example oldSecret123
                     */
                    oldPwd?: string;
                    /**
                     * @description The new password to set (must meet security policy requirements).
                     * @example newSecureP@ssw0rd
                     */
                    newPwd: string;
                    /**
                     * @description Indicates if the user is OAuth-based (no old password check).
                     * @example false
                     */
                    oauth?: boolean;
                };
            };
        };
        responses: {
            /** @description Password successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success: boolean;
                        /** @example Password has been changed. */
                        message: string;
                    };
                };
            };
            /** @description Missing or invalid fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Missing required fields */
                        error: string;
                        /** @example MISSING_FIELDS */
                        code: string;
                    };
                };
            };
            /** @description Invalid credentials or password check failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example Invalid credentials */
                        error: string;
                        /** @example INVALID_CREDENTIALS */
                        code: string;
                    };
                };
            };
            /** @description User not found in the database */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example User not found */
                        error: string;
                        /** @example USER_NOT_FOUND */
                        code: string;
                    };
                };
            };
            /** @description Database or internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        success: boolean;
                        /** @example The database failed */
                        error: string;
                        /** @example DB_FAIL */
                        code: string;
                    };
                };
            };
        };
    };
}
